config/routes.rb
Rails.application.routes.draw do
  root :to => 'pages#home'
  resources :users, :only => [:index, :new, :create]

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  resources :animals
  resources :centers
end

app/models/animal.rb
class Animal < ApplicationRecord
  belongs_to :center, :optional => true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/center.rb
class Center < ApplicationRecord
  has_many :animals
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, :presence => true, :uniqueness => true
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController

  def index
    if params[:animal_species].present?
      @animals = Animal.where :species => params[:animal_species]
    else
      @animals = Animal.all
    end 
  end

  def new
    @animal = Animal.new
  end

  def create
    animal = Animal.create animal_params
    if params[:file].present?
      res = Cloudinary::Uploader.upload(params[:file])
      animal.image = res["public_id"]
    end
    animal.save
    redirect_to animal
  end

  def edit
    @animal = Animal.find params[:id]
  end

  def update
    animal = Animal.find params[:id]
    animal.update animal_params
    if params[:file].present?
      res = Cloudinary::Uploader.upload(params[:file])
      animal.image = res["public_id"]
      animal.save
    end

    redirect_to animal
  end

  def show
    @animal = Animal.find params[:id]
  end

  def destroy
    animal = Animal.find params[:id]
    animal.destroy
    redirect_to animals_path
  end

  private
  def animal_params
    params.require(:animal).permit(:species, :age, :sex, :color, :image, :center_id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :fetch_user


  private
  def fetch_user
    @current_user = User.find_by :id => session[:user_id] if session[:user_id].present?
    session[:user_id] = nil unless @current_user.present?
  end

  def check_for_login
    redirect_to login_path unless @current_user.present?
  end

  def check_for_admin
    redirect_to root_path unless @current_user.present? && @current_user.admin?
  end
end

app/controllers/centers_controller.rb
class CentersController < ApplicationController
  def index
    @centers = Center.all
  end

  def new
    @center = Center.new
  end

  def create
    center = Center.create center_params
    redirect_to center
  end

  def show
    @center = Center.find params[:id]
  end

  def edit
    @center = Center.find params[:id]
  end

  def update
    center = Center.find params[:id]
    center.update center_params
    redirect_to center
  end

  def destroy
    center = Center.find params[:id]
    center.destroy
    redirect_to centers_path
  end

  private
  def center_params
    params.require(:center).permit(:name, :contact, :address)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    user = User.find_by :email => params[:email]
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash[:error] = "Invalid email or password"
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_for_admin, :only => [:index]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create user_params
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end

  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/centers_helper.rb
module CentersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/animals/_form.html.erb
<div class="col-md-4 offset-md-4">
  <%= form_for(@animal, :html => {:multipart => true}) do |f| %>

    <div class="form-group">
      <%= f.label :species %>
      <%= f.text_field :species, :required => true, :autofocus => true %>
    </div>

    <div class="form-group">
      <%= f.label :age %>
      <%= f.text_field :age %>
    </div>

    <div class="form-group">
      <%= f.label :sex %>
      <%= f.text_field :sex %>
    </div>

    <div class="form-group">
      <%= f.label :color %>
      <%= f.text_field :color %>
    </div>

    <div class="form-group">
      <%= f.label :image %>
      <%= f.cl_image_upload :image %>
    </div>

    <div class="form-group">
      <%= f.label :center_id %>
      <%= f.select :center_id, Center.pluck(:name, :id), :include_blank => true %>
    </div>

    <%= f.submit nil, :class => 'btn btn-outline-dark' %>
  <% end %>
</div>

app/views/animals/edit.html.erb
<div class="col-md-4 offset-md-4">
  <h1>Edit Animal Detail</h1>
</div>

<%= render :partial => 'form' %>

app/views/animals/index.html.erb
<div class="col-md-10 offset-md-1">
  <h1>All <%= params[:animal_species].present? ? params[:animal_species]+'s' : 'Animals' %></h1>

  <nav>
    <%= link_to 'Cats', animals_path(:animal_species => 'Cat'), :class =>"index_nav" %>
    <%= link_to 'Dogs', animals_path(:animal_species => 'Dog'), :class =>"index_nav" %>

    <% if @current_user.present? %>
      <% if @current_user.admin? %>
        <%= link_to 'Add Animal', new_animal_path, :class => "index_nav" %>
      <% end %>
    <% end %>
  </nav>

  <% @animals.each do |animal| %>
    <%= link_to cl_image_tag(animal.image, :class => 'thumb', :alt => animal.species), animal %>
  <% end %>
</div>

app/views/animals/new.html.erb
<div class="col-md-4 offset-md-4">
  <h1>Add Animal</h1>
</div>

<%= render :partial => 'form' %>

app/views/animals/show.html.erb
<div class="col-md-10 offset-md-2">

 <div class="row">
    <div class="col-6 col-sm-4">
       <%= cl_image_tag @animal.image, :class =>'feature', :alt => '@animal.species' %>
    </div>

    <div class="col-6 col-sm-6">
      <ul>
        <li class="title list-group-item"><%= @animal.species %></li>
        <li class="list-group-item">Age: <%= @animal.age %></li>
        <li class="list-group-item">Sex: <%= @animal.sex %></li>
        <li class="list-group-item">Color: <%= @animal.color %></li>

        <div class="center_info">
          <% if @animal.center.present? %>
          <li class="list-group-item">Center: <%= link_to @animal.center.name, @animal.center %></li>
          <li class="list-group-item">Contact: <%= number_to_phone @animal.center.contact, :area_code => true %></li>
          <li class="list-group-item">Address: <%= @animal.center.address %></li>
          <% end %>
        </div>
      </ul>
    </div>
  </div>

  <div class="controls">
    <% if @current_user.present? %>
      <% if @current_user.admin? %>
        <%= link_to 'Edit Info', edit_animal_path(@animal) %>
        <%= link_to "Delete this #{ @animal.species }", animal_path(@animal), :method => 'delete' %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/centers/_form.html.erb
<div class="col-md-4 offset-md-4">
  <%= form_for @center do |f| %>

    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, :required => true, :autofocus => true %>
    </div>

    <div class="form-group">
      <%= f.label :contact %>
      <%= f.telephone_field :contact, :placeholder => "0234567890"%>
    </div>

    <div class="form-group">
      <%= f.label :address %>
      <%= f.text_field :address %>
    </div>

    <%= f.submit nil, :class => 'btn btn-outline-dark'  %>
  <% end %>
</div>

app/views/centers/edit.html.erb
<div class="col-md-4 offset-md-4">
  <h1>Edit Center Info</h1>
</div>

<%= render :partial => 'form' %>

app/views/centers/index.html.erb
<div class="col-md-10 offset-md-1">
  <h1>Partners of The Paws Button</h1>

  <nav>
    <% if @current_user.present? %>
      <% if @current_user.admin? %>
        <%= link_to "Add Center", new_center_path, :class =>"index_nav" %>
      <% end %>
    <% end %>
  </nav>

  <div class="list-group">
    <% @centers.each do |center| %>
      <%= link_to center.name, center, :class =>"list-group-item" %>
    <% end %>
  </div>
</div>

app/views/centers/new.html.erb
<div class="col-md-4 offset-md-4">
  <h1>Add Center</h1>
</div>

<%= render :partial => 'form' %>

app/views/centers/show.html.erb
<div class="col-md-8 offset-md-3">
  <h1><%= @center.name %></h1>

  <div class="show_main">
    <ul>
      <li>Name: <%= @center.name %></li>
      <li>Contact: <%= number_to_phone @center.contact, :area_code => true %></li>
      <li>Address: <%= @center.address %></li>
    </ul>

    <% if @center.animals.present? %>
      <% @center.animals.each do |animal| %>
        <%= link_to cl_image_tag(animal.image, :class => 'thumb'), animal %>
      <% end %>
    <% end %>
  </div>

  <div class="controls">
    <% if @current_user.present? %>
      <% if @current_user.admin? %>
        <%= link_to 'Edit Center Info', edit_center_path(@center.id) %>
        <%= link_to 'Delete this Center', center_path(@center.id), :method => 'delete' %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pets</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= cloudinary_js_config %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/2d323a629b.js" crossorigin="anonymous"></script>
    <link href='https://fonts.googleapis.com/css?family=Oswald' rel='stylesheet' type='text/css'>
  </head>

  <body>
    <div class="container">

      <nav class="navbar">
        <div class="nav_logo">
          <i class="fas fa-paw"></i>
          <%= link_to 'The Paws Button', root_path %>
        </div>

        <div class="nav_menu">
          <%= link_to 'Home', root_path %>
          <%= link_to 'Animals', animals_path %>
          <%= link_to 'Centers', centers_path %>
        </div>

        <div class="nav_login">
          <% if @current_user.present? %>
            <% if @current_user.admin? %>
              <%= link_to 'All users', users_path %>
            <% end %>
            <%= link_to "Log out #{ @current_user.email } ", login_path, :method => 'delete' %>
            You are logged in as <%= @current_user.email %>
          <% else %>
            <%= link_to 'Sign up', new_user_path %>
            <%= link_to 'Sign in', login_path %>
          <% end %>
        </div>
      </nav>

      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="home_container">
  <div class="overlay">

    <p class="home_message">Find Your Pet Today!</p>
  </div>
</div>

app/views/session/new.html.erb
<div class="col-md-6 offset-md-3">

  <h1>Sign In</h1>

  <% if flash[:error].present? %>
    <h2><%= flash[:error] %></h2>
  <% end %>

  <%= form_tag login_path do %>
    <div class="form-group">
      <%= label_tag :email %>
      <%= email_field_tag :email, nil, :class => 'form-control' %>
    </div>

    <div class="form-group">
      <%= label_tag :password %>
      <%= password_field_tag :password, nil, :class => 'form-control' %>
    </div>

    <%= submit_tag "Sign In", :class => 'btn btn-outline-dark' %>
  <% end %>

</div>

app/views/users/index.html.erb
<div class="offset-md-1">
  <h1>All Users</h1>

  <% @users.each do |user| %>
    <p><%= user.email %></p>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="col-md-6 offset-md-3">

  <h1>Sign Up</h1>

  <% if @user.errors.any? %>
    <ol>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ol>
  <% end %>

  <%= form_for @user do |f| %>
    <div class="form-group">
      <%= f.label :email %>
      <%= f.email_field :email, :class => 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :password %>
      <%= f.password_field :password, :class => 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, :class => 'form-control' %>
    </div>

    <%= f.submit "Sign Up", :class => 'btn btn-outline-dark' %>
  <% end %>

</div>